### Create restaurant
POST localhost:8080/api/restaurants
Content-Type: application/json

{
  "ownerId": "552cc380-fd95-478f-81c2-bd7d7e5a6598",
  "address": {
    "street": "Jump Street",
    "number": 44,
    "postalCode": "1020",
    "city": "Brussels",
    "country": "Belgium"
  },
  "email": "contact@myrestaurant1.com",
  "pictureURL": "randomURL",
  "defaultPrepTime": 20,
  "cuisineType": "ITALIAN",
  "openingHours": {
    "weeklySchedule": {
    "MONDAY": { "start": "10:00:00", "end": "22:00:00" },
    "TUESDAY": { "start": "10:00:00", "end": "22:00:00" },
    "WEDNESDAY": { "start": "12:00:00", "end": "23:00:00" },
      "THURSDAY": { "start": "12:00:00", "end": "23:00:00" },
      "FRIDAY": { "start": "12:00:00", "end": "23:00:00" },
      "SATURDAY": { "start": "12:00:00", "end": "23:00:00" },
      "SUNDAY": { "start": "12:00:00", "end": "23:00:00" }
    }
  }
}


###

### Create dish as draft
POST localhost:8080/api/drafts
Content-Type: application/json
Accept: application/json

{
  "restaurantId": "f6adce58-e086-4f73-8c9f-aaf38e701e81",
  "name": "Spaghetti Bolognese",
  "description": "Classic Italian pasta with rich beef tomato sauce.",
  "price": 14.99,
  "tags": ["CARNIVORE"],
  "pictureURL": "randomURL",
  "type": "MAIN"
}



###

### Publish a draft
POST localhost:8080/api/dishes
Content-Type: application/json
Accept: application/json

{
  "restaurantId": "f6adce58-e086-4f73-8c9f-aaf38e701e81",
  "draftId": "b57ccdda-4cc4-4803-a844-1ad2e7eee074"
}



###

### Unpublish a dish
PATCH localhost:8080/api/dishes/:unpublish
Content-Type: application/json
Accept: application/json

{
  "dishId": "a661c813-0cd2-46cb-bed6-2cd6ecf053fc",
  "menuId": "f6adce58-e086-4f56-8c9f-aaf38e701e81"
}


###

### Publish a dish
PATCH localhost:8080/api/dishes/:publish
Content-Type: application/json
Accept: application/json

{
  "dishId": "a661c813-0cd2-46cb-bed6-2cd6ecf053fc",
  "menuId": "f6adce58-e086-4f56-8c9f-aaf38e701e81"
}


###

### Mark Dish Out of Stock
PATCH localhost:8080/api/dishes/:outOfStock
Content-Type: application/json
Accept: application/json

{
  "dishId": "a661c813-0cd2-46cb-bed6-2cd6ecf053fc",
  "menuId": "f6adce58-e086-4f56-8c9f-aaf38e701e81"
}


###

### Mark Dish Back In Stock
PATCH localhost:8080/api/dishes/:backInStock
Content-Type: application/json
Accept: application/json

{
  "dishId": "a661c813-0cd2-46cb-bed6-2cd6ecf053fc",
  "menuId": "f6adce58-e086-4f56-8c9f-aaf38e701e81"
}


###


