### Create restaurant
POST localhost:8080/api/restaurants
Content-Type: application/json

{
  "ownerId": "552cc380-fd95-478f-81c2-bd7d7e5a6588",
  "address": {
    "street": "Fellow St.",
    "number": 56,
    "postalCode": "2020",
    "city": "Berlin",
    "country": "Germany"
  },
  "email": "contact@myrestaurant2.com",
  "pictureURL": "randomURL",
  "defaultPrepTime": 30,
  "cuisineType": "ITALIAN",
  "openingHours": {
    "weeklySchedule": {
    "MONDAY": { "start": "10:00:00", "end": "22:00:00" },
    "TUESDAY": { "start": "10:00:00", "end": "22:00:00" },
    "WEDNESDAY": { "start": "12:00:00", "end": "23:00:00" },
      "THURSDAY": { "start": "12:00:00", "end": "23:00:00" },
      "FRIDAY": { "start": "12:00:00", "end": "23:00:00" },
      "SATURDAY": { "start": "12:00:00", "end": "23:00:00" },
      "SUNDAY": { "start": "12:00:00", "end": "23:00:00" }
    }
  }
}


###

### Create dish as draft
POST localhost:8080/api/drafts
Content-Type: application/json
Accept: application/json

{
  "restaurantId": "0c8bf7b5-7330-4d3d-b8f1-2d067b0a6ebc",
  "name": "Pizza Margaritta",
  "description": "Classic Italian pizza",
  "price": 18,
  "tags": ["CARNIVORE"],
  "pictureURL": "someURL",
  "type": "MAIN"
}



###

### Publish a draft
POST localhost:8080/api/dishes
Content-Type: application/json
Accept: application/json

{
  "restaurantId": "0c8bf7b5-7330-4d3d-b8f1-2d067b0a6ebc",
  "draftId": "cd9cb445-0b8e-4519-a5c6-b74c56412fa7"
}



###

### Unpublish a dish
PATCH localhost:8080/api/dishes/:unpublish
Content-Type: application/json
Accept: application/json

{
  "dishId": "f53317ab-163b-4c4b-8fd1-c75eb8c404b2",
  "menuId": "8b8545b6-fe97-4682-acc8-80b695767b44"
}


###

### Publish a dish
PATCH localhost:8080/api/dishes/:publish
Content-Type: application/json
Accept: application/json

{
  "dishId": "f53317ab-163b-4c4b-8fd1-c75eb8c404b2",
  "menuId": "8b8545b6-fe97-4682-acc8-80b695767b44"
}


###

### Mark Dish Out of Stock
PATCH localhost:8080/api/dishes/:outOfStock
Content-Type: application/json
Accept: application/json

{
  "dishId": "f53317ab-163b-4c4b-8fd1-c75eb8c404b2",
  "menuId": "8b8545b6-fe97-4682-acc8-80b695767b44"
}


###

### Mark Dish Back In Stock
PATCH localhost:8080/api/dishes/:backInStock
Content-Type: application/json
Accept: application/json

{
  "dishId": "f53317ab-163b-4c4b-8fd1-c75eb8c404b2",
  "menuId": "8b8545b6-fe97-4682-acc8-80b695767b44"
}


###

### Add item to basket
POST localhost:8080/api/basket/items
Content-Type: application/json
Accept: application/json

{
  "dishId": "2107c228-8577-4048-8406-a30ba8c92944",
  "restaurantId": "9eeec569-d99e-4c03-93bc-f1e152363874",
  "customerSessionId": "9eeec569-d99e-4c03-93bc-f1e152363873"
}


###

### Remove item from basket
DELETE localhost:8080/api/basket/items
Content-Type: application/json

{
  "dishId": "2107c228-8577-4048-8406-a30ba8c92944",
  "basketId": "b961c808-7134-4600-b104-e37bbc716be2"
}


###


