spring.application.name=ivanov_kaloyan_prog6_backend

spring.datasource.url=jdbc:postgresql://localhost:5444/kdg
spring.datasource.username=kdg
spring.datasource.password=kdg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
